### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/hr-holidays#53]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] hr_holidays_auto_extend - By @luisDIXMIT - #136
- [x] hr_holidays_natural_period - By @OsoTranquilo - #79
- [ ] hr_holidays_public - By @yankinmax - #62
- [x] hr_holidays_public_city - By @victoralmau - #96
- [x] hr_holidays_settings - By @JasminSForgeFlow - #120
- [x] hr_holidays_summary_email - By @JasminSForgeFlow - #121
- [x] hr_leave_custom_hour_interval - By @luisDIXMIT - #131

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by pegonzalezspesol** [comment]
Starting to work on hr_holidays_public

**Comment by hailangvn** [comment]
> Starting to work on hr_holidays_public

Thanks @pegonzalezspesol for the note. Is it possible to provide WIP code so that we can have early review?

**Comment by yankinmax** [comment]
don't wait for @pegonzalezspesol and migrating `hr_holidays_public`
https://github.com/OCA/hr-holidays/pull/62

**Comment by OsoTranquilo** [comment]
Starting to work in `hr_holidays_natural_period`

[#76](https://github.com/OCA/hr-holidays/pull/76)
